version: '3.4'

services:
  web.host.service:
    image: ${DOCKER_REGISTRY-}webhostservice
    build:
      context: ./../Web.Host.Service/
      dockerfile: Dev.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
  proxy.front:
    image: ${DOCKER_REGISTRY-}proxy.front
    build:
      context: ./../../src-front/
      dockerfile: Dev.Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8088:80"
    links:
      - web.host.service
