version: '3.4'

services:
  log.service:
    container_name: a1-seq
    image: "datalust/seq:5"
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - a1
  elk.service:
    container_name: a1-elk
    image: "sebp/elk"
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - a1
  web.host.service:
    container_name: a1-webhost
    image: ${DOCKER_REGISTRY-}webhostservice
    build:
      context: ./../Web.Host.Service/
      dockerfile: Dev.Dockerfile
    depends_on:
      - "log.service"
      - "elk.service"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - a1
  proxy.front:
    container_name: a1-proxy
    image: ${DOCKER_REGISTRY-}proxy.front
    build:
      context: ./../../src-front/
      dockerfile: Dev.Dockerfile
    depends_on:
      - web.host.service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./auth.htpasswd:/etc/nginx/auth.htpasswd
    ports:
      - "8088:80"
    networks:
      - a1

networks:
  a1:
    driver: "bridge"